### ISSUE TITLE
Why aren't mobile browsers supported?

### ISSUE THREAD

**Issue by elGatoMantocko** [spotify/web-playback-sdk#10]
I would love to allow my users to use my app on mobile devices as well, and was wondering why Chrome for android (at least) isn't supported. I don't have any knowledge or experience working with browser SDKs, so I couldn't possibly understand the complexity, but I would love to know if there is any future roadmap to add support.

Thanks,

Elliott

**Comment by bih** [comment]
Hey @elGatoMantocko,

It's because mobile browsers supported with the Web Playback SDK don't have [Encrypted Media Extensions (EME)](https://www.w3.org/TR/encrypted-media/) and/or [Widevine](https://www.widevine.com) support which we use as [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) for Spotify content.

Hopefully mobile browsers will adopt these technologies in the future. There is a possibility some nightly builds of mobile browsers that have support for Widevine that we're not aware of, but our official support is for stable versions.

Hope this helps! :)

**Comment by elGatoMantocko** [comment]
Awesome! Thanks so much for the reply!

**Comment by NeoLegends** [comment]
Hey @bih,

I was skimming through other issues and over in #8 you said you are streaming 256kb/s AAC music and here you said you do not support Safari because it only supports AAC-EME, which you do not support right now.

Could you clarify that? Based on what you told it seems like Safari should be supported, no? :) (not wanting to blame you in any way, I'm just curious :) )

**Comment by theiliad** [comment]
@bih Is there a timeline you could share for mobile compatibility?

Playing Spotify right out of the browser on computers is cool, but a very high percentage of users browse sites on their phones.

**Comment by ErezHorev** [comment]
I would really like to use your service but i have no playback at all (nor my friends at office).
This issue seems to be very common here.

Why isn't that being shown with a friendly message with instructions on how to solve?
I have no idea how to solve it. what should be installed? from where? 

The links on @bih response seems for experts, no way i'm going to spend more than a minute on this.  
you guys should get this covered if want users to stay your users rather than another service

Thanks

I'm using macbook OSx 10.13.3 with chrome

**Comment by arirawr** [comment]
Hi @ErezHorev - please open a new issue on this repository with specific steps we can follow to reproduce the issue you're having, and include any error messages you see. That way we'll be able to help you out 😄

**Comment by arirawr** [comment]
It looks like you received some help from the Festify developers on the issue you referenced :)

**Comment by JanneHarju** [comment]
I noticed recently that browser did ask permission automatically for something when using mobile. All works well when using Chrome for Android.

**Comment by paulgoetze** [comment]
It been a year since this issue was opened and it looks like I can still not use the SDK in mobile browsers (Android 8.1 + 9.0 on mobile firefox 64.0.2 and Chrome 69.0.3497.100). I was asked for some access permission once in Chrome, but it did not help to play music in the end. 

@bih Is the support for mobile browsers planned anytime soon? Last year you said your team is going to work on this soonish – do you have any update regarding this? Thinking of Progressive Web Apps it would be such an amazing thing to have the SDK working in mobile browsers on Android at least!

**Comment by cashmash** [comment]
+1 for mobile support/update

**Comment by JanneHarju** [comment]
I think problem is not with spotify sdk problem is with mobile browsers. Spotify sdk is using feature what is not supported in mobile browsers yet. It is called Encrypted Media Extensions. You can read more it from here https://developer.spotify.com/documentation/web-playback-sdk/#supported-browsers
And here https://developers.google.com/web/fundamentals/media/eme

**Comment by JanneHarju** [comment]
Sorry I was wrong https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API

**Comment by tobika** [comment]
Just for info, I'm using the sdk successfully in cordova under android (which is basically a chrome webview) as well as the chrome browser under android. (unfortunately no mobile safari though)

**Comment by Computr0n** [comment]
> Just for info, I'm using the sdk successfully in [...] the chrome browser under android

How are you getting this to work? I can only get it to playback when I tell chrome to load the page in desktop mode....
