### ISSUE TITLE
Playback Sdk on Electron: Failed to initialize player

### ISSUE THREAD

**Issue by tymmesyde** [spotify/web-playback-sdk#41]
Hello !
So i'm using this sdk with Electron, i've managed to import it correctly.

The scope i'm using :  
```
'user-read-currently-playing',
'user-read-playback-state',
'user-modify-playback-state',
'streaming',
'user-read-email',
'user-read-birthdate',
'user-read-private'
```

When i initialize it after `onSpotifyWebPlaybackSDKReady` with a working `accessToken`, I've got this two Warnings :
`[Deprecation] requestMediaKeySystemAccess usage in cross-origin iframes is deprecated and will be disabled in M63, around December 2017. To continue to use this feature, it must be enabled by the embedding document using Feature Policy, e.g. <iframe allow="encrypted-media" ...>. See https://goo.gl/EuHzyv for more details.`

`
It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior, potentially including failure to play.`

And this Error :
`Failed to initialize player`

I serve my Electron App on localhost so it should not be the problem ?
Can you help me on what could be causing this ?

**Comment by arirawr** [comment]
Hey @tymmesyde, have you checked out #7? Electron doesn't support Widevine CDM and you'll need the proper licenses in order to make an application.

**Comment by tymmesyde** [comment]
Thank for your quick response !
It seems that Widevine is successfully loaded: checked with navigator.plugins.
Plus it doesn't throw me the Widevine error like on #7.

**Comment by stephanepericat** [comment]
<img width="1436" alt="screen shot 2018-08-26 at 3 43 14 pm" src="https://user-images.githubusercontent.com/161823/44632810-e46db500-a946-11e8-92df-07fc03fd9f8c.png">

I am also running into an issue trying to instantiate a player device in electron 2.0.8.
Same code works fine in Chrome 68.0.3440.106

**Comment by JeanBarriere** [comment]
Same error here. Anything ?

**Comment by Arinono** [comment]
I'm having the same issue. Is there anything new ?

**Comment by starkkg12** [comment]
I'm having the same issue.

**Comment by palmadias** [comment]
I'm having the same issue.

**Comment by minestarnl** [comment]
same issue here

**Comment by stephanepericat** [comment]
@spotify any update on this issue ? Are you guys just never gonna support Electron ?

**Comment by tymmesyde** [comment]
What's weird is that it worked very well with Electron a while back. I even tried the old version of the script again, which was supposed to work before but no changes were seen.

**Comment by kalvinpearce** [comment]
@spotify would love an update on this. It looks like the spotify desktop app on windows includes their own version of WidevineCDM. I am not sure how they link to it of if they even use the same SDK for their client

**Comment by BelphegorPrime** [comment]
@spotify I followed the [quick-start tutorial](https://developer.spotify.com/documentation/web-playback-sdk/quick-start/actually) but with chromium 70.0.3538.110 and for me more important electron 3.0.9 (Chromium 66.0.3359.181), the initialization_error Listener is triggering with the error 
```
    message: "Failed to initialize player"
```
but with google chrome 71.0.3578.80 initialization works fine

Encrypted Media Extensions as mentioned [here](https://developer.spotify.com/documentation/web-playback-sdk/reference/#error-initialization-error) should be part since Chromium version [42](https://www.chromestatus.com/feature/6578378068983808)

**Comment by stephanepericat** [comment]
I'm starting to think that @spotify is purposely ignoring the problem so we can't build desktop apps with the API...

**Comment by smadigan91** [comment]
Also having this issue on Chromium 60.0.3112.89 fwiw

**Comment by groovybytes** [comment]
same issue here :)

**Comment by smadigan91** [comment]
So after a couple attempts to hack this to work, I got closer but couldn't quite get it working -  the SDK initializes playback, starts playing a song, but seems to fail after that. 

I _think_ the issue here, at least the issue with encrypted-media not working, has to do with the fact that chromium doesn't officially support Widevine. I checked [here](https://wiki.archlinux.org/index.php/chromium#Widevine_Content_Decryption_Module_plugin) and on various forums to see how one could add widevine support to chromium, ended up following [this](https://thepi.io/how-to-watch-netflix-on-the-raspberry-pi/) tutorial, and it _almost_ worked as described above. I noticed in the network console there were repeated calls from what appeared to be the web playback SDK to retrieve a widevine license that were failing with a 400, I'm guessing because either that tutorial is old or the widevine plugin is unofficial, not sure which. I might give this another shot as I see there are some different tutorials on how to do this but I'm not terribly optimistic

**Comment by Plopkonijn** [comment]
Why has it been closed? I can't find

**Comment by BelphegorPrime** [comment]
@Plopkonijn 
Well the easiest way I could found was to use [castlabs/electron-releases](https://github.com/castlabs/electron-releases).

[Here](https://github.com/BelphegorPrime/dsa) is the repository for which I needed the Widevine support.
